In [2]:

from google.colab import files

uploaded = files.upload()

Saving IBM_HR_Analytics.csv to IBM_HR_Analytics.csv

In [3]:

import pandas as pd
import numpy as np

df = pd.read_csv("/content/IBM_HR_Analytics.csv")

print("Dataset loaded successfully!")
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

df.head()

Dataset loaded successfully!
Number of rows: 1470
Number of columns: 35

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

Warning: Total number of columns (35) exceeds max_columns (20) limiting to first (20) columns.

In [4]:

# Display all column names
print("COLUMN NAMES:")
print(df.columns.tolist())

# Check data types and non-null values
print("\nDATASET INFORMATION:")
df.info()

COLUMN NAMES:
['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department', 'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount', 'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']

DATASET INFORMATION:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [5]:

# Count missing values in each column
missing_values = df.isnull().sum()

print("Missing values in each column:")
print(missing_values)

print("\nTotal missing values:", missing_values.sum())

Missing values in each column:
Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

Total missing values: 0

In [6]:

# Count exact duplicate rows
duplicate_count = df.duplicated().sum()

print("Total rows:", len(df))
print("Exact duplicate rows:", duplicate_count)

Total rows: 1470
Exact duplicate rows: 0

In [7]:

# Check whether EmployeeNumber is unique
duplicate_employee_ids = df["EmployeeNumber"].duplicated().sum()

print("Total employee records:", len(df))
print("Unique employee IDs:", df["EmployeeNumber"].nunique())
print("Duplicate employee IDs:", duplicate_employee_ids)

Total employee records: 1470
Unique employee IDs: 1470
Duplicate employee IDs: 0

In [8]:

# Check the distinct values in these three columns
columns_to_check = ["EmployeeCount", "Over18", "StandardHours"]

for column in columns_to_check:
    print(f"\n{column}:")
    print(df[column].value_counts(dropna=False))

EmployeeCount:
EmployeeCount
1    1470
Name: count, dtype: int64

Over18:
Over18
Y    1470
Name: count, dtype: int64

StandardHours:
StandardHours
80    1470
Name: count, dtype: int64

In [9]:

# Create a separate copy for analysis
df_clean = df.copy()

# Remove columns confirmed to have constant values
columns_to_remove = ["EmployeeCount", "Over18", "StandardHours"]

df_clean = df_clean.drop(columns=columns_to_remove)

print("Original dataset shape:", df.shape)
print("Analysis dataset shape:", df_clean.shape)
print("\nRemaining columns:", df_clean.shape[1])
print("\nRemoved columns:", columns_to_remove)

Original dataset shape: (1470, 35)
Analysis dataset shape: (1470, 32)

Remaining columns: 32

Removed columns: ['EmployeeCount', 'Over18', 'StandardHours']

In [10]:

# 1. Check the numerical ranges
print("NUMERICAL SUMMARY:")
display(df_clean.describe().T)

# 2. Check important categorical values
categorical_columns = [
    "Attrition",
    "Department",
    "Gender",
    "OverTime",
    "BusinessTravel",
    "MaritalStatus"
]

print("\nCATEGORICAL VALUE CHECKS:")

for column in categorical_columns:
    print(f"\n{column}:")
    print(df_clean[column].value_counts(dropna=False))

NUMERICAL SUMMARY:

,count,mean,std,min,25%,50%,75%,max
Age,1470.0,36.923810,9.135373,18.0,30.00,36.0,43.00,60.0
DailyRate,1470.0,802.485714,403.509100,102.0,465.00,802.0,1157.00,1499.0
DistanceFromHome,1470.0,9.192517,8.106864,1.0,2.00,7.0,14.00,29.0
Education,1470.0,2.912925,1.024165,1.0,2.00,3.0,4.00,5.0
EmployeeNumber,1470.0,1024.865306,602.024335,1.0,491.25,1020.5,1555.75,2068.0
EnvironmentSatisfaction,1470.0,2.721769,1.093082,1.0,2.00,3.0,4.00,4.0
HourlyRate,1470.0,65.891156,20.329428,30.0,48.00,66.0,83.75,100.0
JobInvolvement,1470.0,2.729932,0.711561,1.0,2.00,3.0,3.00,4.0
JobLevel,1470.0,2.063946,1.106940,1.0,1.00,2.0,3.00,5.0
JobSatisfaction,1470.0,2.728571,1.102846,1.0,2.00,3.0,4.00,4.0
MonthlyIncome,1470.0,6502.931293,4707.956783,1009.0,2911.00,4919.0,8379.00,19999.0
MonthlyRate,1470.0,14313.103401,7117.786044,2094.0,8047.00,14235.5,20461.50,26999.0
NumCompaniesWorked,1470.0,2.693197,2.498009,0.0,1.00,2.0,4.00,9.0
PercentSalaryHike,1470.0,15.209524,3.659938,11.0,12.00,14.0,18.00,25.0
PerformanceRating,1470.0,3.153741,0.360824,3.0,3.00,3.0,3.00,4.0
RelationshipSatisfaction,1470.0,2.712245,1.081209,1.0,2.00,3.0,4.00,4.0
StockOptionLevel,1470.0,0.793878,0.852077,0.0,0.00,1.0,1.00,3.0
TotalWorkingYears,1470.0,11.279592,7.780782,0.0,6.00,10.0,15.00,40.0
TrainingTimesLastYear,1470.0,2.799320,1.289271,0.0,2.00,3.0,3.00,6.0
WorkLifeBalance,1470.0,2.761224,0.706476,1.0,2.00,3.0,3.00,4.0
YearsAtCompany,1470.0,7.008163,6.126525,0.0,3.00,5.0,9.00,40.0
YearsInCurrentRole,1470.0,4.229252,3.623137,0.0,2.00,3.0,7.00,18.0
YearsSinceLastPromotion,1470.0,2.187755,3.222430,0.0,0.00,1.0,3.00,15.0
YearsWithCurrManager,1470.0,4.123129,3.568136,0.0,2.00,3.0,7.00,17.0

CATEGORICAL VALUE CHECKS:

Attrition:
Attrition
No     1233
Yes     237
Name: count, dtype: int64

Department:
Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64

Gender:
Gender
Male      882
Female    588
Name: count, dtype: int64

OverTime:
OverTime
No     1054
Yes     416
Name: count, dtype: int64

BusinessTravel:
BusinessTravel
Travel_Rarely        1043
Travel_Frequently     277
Non-Travel            150
Name: count, dtype: int64

MaritalStatus:
MaritalStatus
Married     673
Single      470
Divorced    327
Name: count, dtype: int64

In [11]:

rating_columns = [
    "JobSatisfaction",
    "EnvironmentSatisfaction",
    "RelationshipSatisfaction",
    "JobInvolvement",
    "WorkLifeBalance"
]

for column in rating_columns:
    print(f"{column}: {sorted(df_clean[column].unique())}")

JobSatisfaction: [np.int64(1), np.int64(2), np.int64(3), np.int64(4)]
EnvironmentSatisfaction: [np.int64(1), np.int64(2), np.int64(3), np.int64(4)]
RelationshipSatisfaction: [np.int64(1), np.int64(2), np.int64(3), np.int64(4)]
JobInvolvement: [np.int64(1), np.int64(2), np.int64(3), np.int64(4)]
WorkLifeBalance: [np.int64(1), np.int64(2), np.int64(3), np.int64(4)]

In [12]:

# Create readable labels without changing the original rating columns

satisfaction_labels = {
    1: "Low",
    2: "Medium",
    3: "High",
    4: "Very High"
}

work_life_labels = {
    1: "Bad",
    2: "Good",
    3: "Better",
    4: "Best"
}

df_clean["JobSatisfactionLabel"] = (
    df_clean["JobSatisfaction"].map(satisfaction_labels)
)

df_clean["EnvironmentSatisfactionLabel"] = (
    df_clean["EnvironmentSatisfaction"].map(satisfaction_labels)
)

df_clean["RelationshipSatisfactionLabel"] = (
    df_clean["RelationshipSatisfaction"].map(satisfaction_labels)
)

df_clean["JobInvolvementLabel"] = (
    df_clean["JobInvolvement"].map(satisfaction_labels)
)

df_clean["WorkLifeBalanceLabel"] = (
    df_clean["WorkLifeBalance"].map(work_life_labels)
)

print("Readable rating labels created successfully!")
display(
    df_clean[
        [
            "JobSatisfaction",
            "JobSatisfactionLabel",
            "WorkLifeBalance",
            "WorkLifeBalanceLabel"
        ]
    ].head()
)

Readable rating labels created successfully!

   JobSatisfaction JobSatisfactionLabel  WorkLifeBalance WorkLifeBalanceLabel
0                4            Very High                1                  Bad
1                2               Medium                3               Better
2                3                 High                3               Better
3                3                 High                3               Better
4                2               Medium                3               Better

In [13]:

total_employees = len(df_clean)

employees_left = (df_clean["Attrition"] == "Yes").sum()
employees_stayed = (df_clean["Attrition"] == "No").sum()

attrition_rate = (employees_left / total_employees) * 100
average_age = df_clean["Age"].mean()
average_monthly_income = df_clean["MonthlyIncome"].mean()
average_years_at_company = df_clean["YearsAtCompany"].mean()

print("HR EXECUTIVE METRICS")
print("-" * 35)

print("Total Employees:", total_employees)
print("Employees Who Left:", employees_left)
print("Employees Who Stayed:", employees_stayed)
print(f"Attrition Rate: {attrition_rate:.2f}%")
print(f"Average Age: {average_age:.2f} years")
print(f"Average Monthly Income: {average_monthly_income:.2f}")
print(f"Average Years at Company: {average_years_at_company:.2f}")

HR EXECUTIVE METRICS
-----------------------------------
Total Employees: 1470
Employees Who Left: 237
Employees Who Stayed: 1233
Attrition Rate: 16.12%
Average Age: 36.92 years
Average Monthly Income: 6502.93
Average Years at Company: 7.01

In [14]:

department_analysis = (
    df_clean.groupby("Department")
    .agg(
        TotalEmployees=("EmployeeNumber", "count"),
        EmployeesLeft=("Attrition", lambda x: (x == "Yes").sum())
    )
    .reset_index()
)

department_analysis["AttritionRate"] = (
    department_analysis["EmployeesLeft"]
    / department_analysis["TotalEmployees"]
    * 100
)

department_analysis = department_analysis.sort_values(
    "AttritionRate", ascending=False
)

department_analysis["AttritionRate"] = (
    department_analysis["AttritionRate"].round(2)
)

display(department_analysis)

               Department  TotalEmployees  EmployeesLeft  AttritionRate
2                   Sales             446             92          20.63
0         Human Resources              63             12          19.05
1  Research & Development             961            133          13.84

In [15]:

job_role_analysis = (
    df_clean.groupby("JobRole")
    .agg(
        TotalEmployees=("EmployeeNumber", "count"),
        EmployeesLeft=("Attrition", lambda x: (x == "Yes").sum())
    )
    .reset_index()
)

job_role_analysis["AttritionRate"] = (
    job_role_analysis["EmployeesLeft"]
    / job_role_analysis["TotalEmployees"]
    * 100
)

job_role_analysis = job_role_analysis.sort_values(
    "AttritionRate", ascending=False
)

job_role_analysis["AttritionRate"] = (
    job_role_analysis["AttritionRate"].round(2)
)

display(job_role_analysis)

                     JobRole  TotalEmployees  EmployeesLeft  AttritionRate
8       Sales Representative              83             33          39.76
2      Laboratory Technician             259             62          23.94
1            Human Resources              52             12          23.08
7            Sales Executive             326             57          17.48
6         Research Scientist             292             47          16.10
4     Manufacturing Director             145             10           6.90
0  Healthcare Representative             131              9           6.87
3                    Manager             102              5           4.90
5          Research Director              80              2           2.50

In [16]:

overtime_analysis = (
    df_clean.groupby("OverTime")
    .agg(
        TotalEmployees=("EmployeeNumber", "count"),
        EmployeesLeft=("Attrition", lambda x: (x == "Yes").sum())
    )
    .reset_index()
)

overtime_analysis["AttritionRate"] = (
    overtime_analysis["EmployeesLeft"]
    / overtime_analysis["TotalEmployees"]
    * 100
)

overtime_analysis["AttritionRate"] = (
    overtime_analysis["AttritionRate"].round(2)
)

display(overtime_analysis)

  OverTime  TotalEmployees  EmployeesLeft  AttritionRate
0       No            1054            110          10.44
1      Yes             416            127          30.53

In [17]:
income_analysis = (
    df_clean.groupby("Attrition")
    .agg(
        EmployeeCount=("EmployeeNumber", "count"),
        AverageMonthlyIncome=("MonthlyIncome", "mean"),
        MedianMonthlyIncome=("MonthlyIncome", "median")
    )
    .reset_index()
)

income_analysis["AverageMonthlyIncome"] = (
    income_analysis["AverageMonthlyIncome"].round(2)
)

income_analysis["MedianMonthlyIncome"] = (
    income_analysis["MedianMonthlyIncome"].round(2)
)

display(income_analysis)

  Attrition  EmployeeCount  AverageMonthlyIncome  MedianMonthlyIncome
0        No           1233               6832.74               5204.0
1       Yes            237               4787.09               3202.0

In [18]:
tenure_analysis = (
    df_clean.groupby("Attrition")
    .agg(
        EmployeeCount=("EmployeeNumber", "count"),
        AverageYearsAtCompany=("YearsAtCompany", "mean"),
        MedianYearsAtCompany=("YearsAtCompany", "median")
    )
    .reset_index()
)

tenure_analysis["AverageYearsAtCompany"] = (
    tenure_analysis["AverageYearsAtCompany"].round(2)
)

display(tenure_analysis)

  Attrition  EmployeeCount  AverageYearsAtCompany  MedianYearsAtCompany
0        No           1233                   7.37                   6.0
1       Yes            237                   5.13                   3.0

In [19]:
satisfaction_analysis = (
    df_clean.groupby("JobSatisfaction")
    .agg(
        TotalEmployees=("EmployeeNumber", "count"),
        EmployeesLeft=("Attrition", lambda x: (x == "Yes").sum())
    )
    .reset_index()
)

satisfaction_analysis["AttritionRate"] = (
    satisfaction_analysis["EmployeesLeft"]
    / satisfaction_analysis["TotalEmployees"]
    * 100
).round(2)

satisfaction_analysis["SatisfactionLabel"] = (
    satisfaction_analysis["JobSatisfaction"].map({
        1: "Low",
        2: "Medium",
        3: "High",
        4: "Very High"
    })
)

display(satisfaction_analysis)

,JobSatisfaction,TotalEmployees,EmployeesLeft,AttritionRate,SatisfactionLabel
0,1,289,66,22.84,Low
1,2,280,46,16.43,Medium
2,3,442,73,16.52,High
3,4,459,52,11.33,Very High

In [20]:
travel_analysis = (
    df_clean.groupby("BusinessTravel")
    .agg(
        TotalEmployees=("EmployeeNumber", "count"),
        EmployeesLeft=("Attrition", lambda x: (x == "Yes").sum())
    )
    .reset_index()
)

travel_analysis["AttritionRate"] = (
    travel_analysis["EmployeesLeft"]
    / travel_analysis["TotalEmployees"]
    * 100
).round(2)

display(travel_analysis)

      BusinessTravel  TotalEmployees  EmployeesLeft  AttritionRate
0         Non-Travel             150             12           8.00
1  Travel_Frequently             277             69          24.91
2      Travel_Rarely            1043            156          14.96

In [21]:
df_clean["AgeGroup"] = pd.cut(
    df_clean["Age"],
    bins=[17, 25, 35, 45, 55, 60],
    labels=[
        "18-25",
        "26-35",
        "36-45",
        "46-55",
        "56-60"
    ]
)

age_analysis = (
    df_clean.groupby("AgeGroup", observed=False)
    .agg(
        TotalEmployees=("EmployeeNumber", "count"),
        EmployeesLeft=("Attrition", lambda x: (x == "Yes").sum())
    )
    .reset_index()
)

age_analysis["AttritionRate"] = (
    age_analysis["EmployeesLeft"]
    / age_analysis["TotalEmployees"]
    * 100
).round(2)

display(age_analysis)

  AgeGroup  TotalEmployees  EmployeesLeft  AttritionRate
0    18-25             123             44          35.77
1    26-35             606            116          19.14
2    36-45             468             43           9.19
3    46-55             226             26          11.50
4    56-60              47              8          17.02

In [22]:
gender_analysis = (
    df_clean.groupby("Gender")
    .agg(
        TotalEmployees=("EmployeeNumber", "count"),
        EmployeesLeft=("Attrition", lambda x: (x == "Yes").sum())
    )
    .reset_index()
)

gender_analysis["AttritionRate"] = (
    gender_analysis["EmployeesLeft"]
    / gender_analysis["TotalEmployees"]
    * 100
).round(2)

display(gender_analysis)

   Gender  TotalEmployees  EmployeesLeft  AttritionRate
0  Female             588             87          14.80
1    Male             882            150          17.01

In [23]:
marital_analysis = (
    df_clean.groupby("MaritalStatus")
    .agg(
        TotalEmployees=("EmployeeNumber", "count"),
        EmployeesLeft=("Attrition", lambda x: (x == "Yes").sum())
    )
    .reset_index()
)

marital_analysis["AttritionRate"] = (
    marital_analysis["EmployeesLeft"]
    / marital_analysis["TotalEmployees"]
    * 100
).round(2)

display(marital_analysis)

  MaritalStatus  TotalEmployees  EmployeesLeft  AttritionRate
0      Divorced             327             33          10.09
1       Married             673             84          12.48
2        Single             470            120          25.53

In [24]:
jobrole_analysis = (
    df_clean.groupby("JobRole")
    .agg(
        TotalEmployees=("EmployeeNumber", "count"),
        EmployeesLeft=("Attrition", lambda x: (x == "Yes").sum())
    )
    .reset_index()
)

jobrole_analysis["AttritionRate"] = (
    jobrole_analysis["EmployeesLeft"]
    / jobrole_analysis["TotalEmployees"]
    * 100
).round(2)

jobrole_analysis = jobrole_analysis.sort_values(
    "AttritionRate",
    ascending=False
)

display(jobrole_analysis)

                     JobRole  TotalEmployees  EmployeesLeft  AttritionRate
8       Sales Representative              83             33          39.76
2      Laboratory Technician             259             62          23.94
1            Human Resources              52             12          23.08
7            Sales Executive             326             57          17.48
6         Research Scientist             292             47          16.10
4     Manufacturing Director             145             10           6.90
0  Healthcare Representative             131              9           6.87
3                    Manager             102              5           4.90
5          Research Director              80              2           2.50

In [25]:
joblevel_analysis = (
    df_clean.groupby("JobLevel")
    .agg(
        TotalEmployees=("EmployeeNumber", "count"),
        EmployeesLeft=("Attrition", lambda x: (x == "Yes").sum())
    )
    .reset_index()
)

joblevel_analysis["AttritionRate"] = (
    joblevel_analysis["EmployeesLeft"]
    / joblevel_analysis["TotalEmployees"]
    * 100
).round(2)

display(joblevel_analysis)

   JobLevel  TotalEmployees  EmployeesLeft  AttritionRate
0         1             543            143          26.34
1         2             534             52           9.74
2         3             218             32          14.68
3         4             106              5           4.72
4         5              69              5           7.25

In [26]:
role_tenure_analysis = (
    df_clean.groupby("YearsInCurrentRole")
    .agg(
        TotalEmployees=("EmployeeNumber", "count"),
        EmployeesLeft=("Attrition", lambda x: (x == "Yes").sum())
    )
    .reset_index()
)

role_tenure_analysis["AttritionRate"] = (
    role_tenure_analysis["EmployeesLeft"]
    / role_tenure_analysis["TotalEmployees"]
    * 100
).round(2)

display(role_tenure_analysis)

    YearsInCurrentRole  TotalEmployees  EmployeesLeft  AttritionRate
0                    0             244             73          29.92
1                    1              57             11          19.30
2                    2             372             68          18.28
3                    3             135             16          11.85
4                    4             104             15          14.42
5                    5              36              1           2.78
6                    6              37              2           5.41
7                    7             222             31          13.96
8                    8              89              7           7.87
9                    9              67              6           8.96
10                  10              29              2           6.90
11                  11              22              0           0.00
12                  12              10              1          10.00
13                  13              14              1           7.14
14                  14              11              1           9.09
15                  15               8              2          25.00
16                  16               7              0           0.00
17                  17               4              0           0.00
18                  18               2              0           0.00

In [27]:
key_findings = pd.DataFrame({
    "Analysis": [
        "Overall",
        "Department",
        "Job Role",
        "Overtime",
        "Monthly Income",
        "Company Tenure",
        "Job Satisfaction",
        "Business Travel",
        "Age Group",
        "Gender",
        "Marital Status",
        "Job Level",
        "Current Role Tenure"
    ],
    "Key Finding": [
        "Overall attrition rate is 16.12%",
        "Sales has the highest department attrition rate at 20.63%",
        "Sales Representatives have the highest job-role attrition rate at 39.76%",
        "Overtime employees have a 30.53% attrition rate versus 10.44% for others",
        "Employees who left have lower average monthly income",
        "Employees who left have shorter average company tenure",
        "Low job satisfaction has the highest attrition rate at 22.84%",
        "Frequent business travelers have the highest rate at 24.91%",
        "Employees aged 18-25 have the highest rate at 35.77%",
        "Male attrition is 17.01% versus 14.80% for female employees",
        "Single employees have the highest rate at 25.53%",
        "Job Level 1 has the highest attrition rate at 26.34%",
        "Employees with 0 years in their current role have a 29.92% rate"
    ]
})

display(key_findings)

               Analysis                                        Key Finding
0               Overall                   Overall attrition rate is 16.12%
1            Department  Sales has the highest department attrition rat...
2              Job Role  Sales Representatives have the highest job-rol...
3              Overtime  Overtime employees have a 30.53% attrition rat...
4        Monthly Income  Employees who left have lower average monthly ...
5        Company Tenure  Employees who left have shorter average compan...
6      Job Satisfaction  Low job satisfaction has the highest attrition...
7       Business Travel  Frequent business travelers have the highest r...
8             Age Group  Employees aged 18-25 have the highest rate at ...
9                Gender  Male attrition is 17.01% versus 14.80% for fem...
10       Marital Status   Single employees have the highest rate at 25.53%
11            Job Level  Job Level 1 has the highest attrition rate at ...
12  Current Role Tenure  Employees with 0 years in their current role h...

In [28]:
df_powerbi = df_clean.copy()

df_powerbi["AttritionFlag"] = (
    df_powerbi["Attrition"].map({"Yes": 1, "No": 0})
)

print("Dataset shape:", df_powerbi.shape)
print("\nAttrition flag values:")
print(df_powerbi["AttritionFlag"].value_counts().sort_index())

print("\nMissing values:", df_powerbi.isnull().sum().sum())
print("Duplicate rows:", df_powerbi.duplicated().sum())

Dataset shape: (1470, 39)

Attrition flag values:
AttritionFlag
0    1233
1     237
Name: count, dtype: int64

Missing values: 0
Duplicate rows: 0

In [29]:
df_powerbi.to_csv(
    "IBM_HR_Analytics_PowerBI.csv",
    index=False
)

print("Export completed successfully!")
print("File name: IBM_HR_Analytics_PowerBI.csv")

Export completed successfully!
File name: IBM_HR_Analytics_PowerBI.csv